export const initAutoCompleteWilaya = () => {
    const wilaya = [
        "ADRAR",
        "AIN DEFLA",
        "AIN TEMOUCHENT",
        "AL TARF",
        "ALGER",
        "ANNABA",
        "B.B.ARRERIDJ",
        "BATNA",
        "BECHAR",
        "BEJAIA",
        "BISKRA",
        "BLIDA",
        "BOUIRA",
        "BOUMERDES",
        "CHLEF",
        "CONSTANTINE",
        "DJELFA",
        "EL BAYADH",
        "EL OUED",
        "GHARDAIA",
        "GUELMA",
        "ILLIZI",
        "JIJEL",
        "KHENCHELA",
        "LAGHOUAT",
        "MASCARA",
        "MEDEA",
        "MILA",
        "MOSTAGANEM",
        "M’SILA",
        "NAAMA",
        "ORAN",
        "OUARGLA",
        "OUM ELBOUAGHI",
        "RELIZANE",
        "SAIDA",
        "SETIF",
        "SIDI BEL ABBES",
        "SKIKDA",
        "SOUKAHRAS",
        "TAMANGHASSET",
        "TEBESSA",
        "TIARET",
        "TINDOUF",
        "TIPAZA",
        "TISSEMSILT",
        "TIZI.OUZOU",
        "TLEMCEN",
    ];

    const wilayaElement = document.querySelector("#wilaya");
    wilayaElement?.autocomplete({ source: wilaya });
};
